version: '3.3'
services:
  angular-service:
    container_name: project_angular
    build: ./insight-front
    volumes:
      - './insight-front:/usr/src/app'
    ports: 
      - '4200:4200'
    command: 
      - /bin/sh
      - '-c'
      - 'npm install && ng serve --port 4200 --host 0.0.0.0'
    links: 
      - node
    networks: 
      - my-network
networks:
  my-network:
    driver: bridge
